{
 "title": "Aruba - AOS 8 Cluster Monitoring",
 "tags": [
  "aruba",
  "graphite"
 ],
 "time": { "from": "now-6h", "to": "now-1m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "controller", "label": "Controller", "query": "wlan.aruba.*" }
  ]
 },
 "panels": [
  {
   "title": "APs Deployed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(maxSeries(wlan.aruba.$controller.total_aps), 'Total APs')"
    }
   ]
  },
  {
   "title": "Current Wi-Fi Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "alias(sumSeries(wlan.aruba.$controller.total_assoc), 'Total')"
    }
   ]
  },
  {
   "title": "Current 5GHz Wi-Fi Clients",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "asPercent(sumSeries(wlan.aruba.$controller.assoc.band.5ghz), #A)",
     "targetFull": "asPercent(sumSeries(wlan.aruba.$controller.assoc.band.5ghz), alias(sumSeries(wlan.aruba.$controller.total_assoc), 'Total'))"
    }
   ]
  },
  {
   "title": "Current Wi-Fi Traffic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "format": "bps",
   "valueName": "current",
   "targets": [
    {
     "target": "perSecond(scale(sumSeries(wlan.aruba.$controller.bytes.band.2ghz.tx, wlan.aruba.$controller.bytes.band.2ghz.rx, wlan.aruba.$controller.bytes.band.5ghz.tx, wlan.aruba.$controller.bytes.band.5ghz.rx), 8))"
    }
   ]
  },
  {
   "title": "Cluster Datapath Sessions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "aliasByNode(sumSeries(wlan.aruba.$controller.datapath.*), 2)"
    }
   ]
  },
  {
   "title": "Total Wi-Fi Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(scaleToSeconds(scale(wlan.aruba.$controller.bytes.band.5ghz.tx, 8), 1), 8)), '5GHz TX')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(scaleToSeconds(scale(wlan.aruba.$controller.bytes.band.5ghz.rx, 8), 1), 8)), '5GHz RX')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(scaleToSeconds(scale(wlan.aruba.$controller.bytes.band.2ghz.tx, 8), 1), 8)), '2.4GHz TX')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(scaleToSeconds(scale(wlan.aruba.$controller.bytes.band.2ghz.rx, 8), 1), 8)), '2.4GHz RX')"
    }
   ]
  },
  {
   "title": "Cluster - MD User Table Entries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.total_assoc, 2)"
    },
    {
     "target": "alias(sumSeries(wlan.aruba.$controller.total_assoc), 'Total')"
    }
   ]
  },
  {
   "title": "Cluster - Stations per ESSID",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(wlan.aruba.$controller.assoc.essid.*, 'true'), 5)"
    }
   ]
  },
  {
   "title": "AP Radio Channels (5GHz)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(wlan.aruba.$controller.radio.*.5ghz.channel, 'true'), 4)"
    }
   ]
  },
  {
   "title": "AP Radio Channels (2.4GHz)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sortByName(wlan.aruba.$controller.radio.*.2ghz.channel, 'true'), 4)"
    }
   ]
  },
  {
   "title": "Cluster - MD CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.cpu_used, 2)"
    }
   ]
  },
  {
   "title": "Cluster - MD CPU Utilisation per Core",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.cpu_util.*, 2, 4)"
    }
   ]
  },
  {
   "title": "Cluster - MD Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.memory_used, 2)"
    }
   ]
  },
  {
   "title": "Cluster - MD Datapth Sessions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.datapath.*, 2)"
    }
   ]
  },
  {
   "title": "Cluster - MD Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "target": "aliasByNode(wlan.aruba.$controller.internal_temparature, 2)"
    }
   ]
  },
  {
   "title": "Cluster - Total Registered APs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(maxSeries(wlan.aruba.$controller.total_aps), 'APs')"
    }
   ]
  }
 ]
}